### ISSUE TITLE
Package metadata are missing (`package.xml`)

### ISSUE THREAD

**Issue by galou** [jonbitzen/PartCentroidWorkbench#1]
The file [package.xml](https://wiki.freecad.org/Package_Metadata) is missing in order to allow better integration into the Addon Manager.

**Comment by jonbitzen** [comment]
Gaël, thank you very much for your feedback!  I've added a package.xml file, and tested it by adding my workbench as external repository, and now it shows up in the Addons list like the others.

Thanks again!

Jon
